### ISSUE TITLE
GIFs will be converted to LV_IMG_CF_RAW_CHROMA_KEYED format

### ISSUE THREAD

**Issue by HaoboGu** [lvgl/lv_img_conv#28]
Hello, I'm using [online converter](https://lvgl.io/tools/imageconverter) converting gifs to c array. But the converted c file cannot be displayed with lvgl. I notice that the `.header.cf` field is `LV_IMG_CF_RAW_CHROMA_KEYED`, not `LV_IMG_CF_RAW`. Is this a bug for converting gifs?

I tried [this gif c array](https://github.com/lvgl/lvgl/blob/master/examples/libs/gif/img_bulb_gif.c), it can be displayed perfectly. So it's not a problem of lvgl itself.

**Comment by embeddedt** [comment]
The original PHP converter [didn't seem to distinguish](https://github.com/lvgl/lv_utils/blob/7c851aa04b542190a0ce61ab41b26946ab4c2b83/img_conv_core.php#L41-L43) between images with and without chroma keying, which is why the new converter outputs a chroma keyed header instead of a raw header.

Does it work when you replace the header with `LV_IMG_CF_RAW`?

**Comment by HaoboGu** [comment]
Thanks for the reply! I addressed the problem by increasing the mem size. Not the converter's issue, closing this.
